# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - test
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375

before_script:
  - export DOCKER_HOST

test_a:
  image: markhobson/maven-chrome
  stage: test
  script:
    - mvn clean test

test_b:
  image: maven:3.8.4-openjdk-17-slim
  stage: test
  services:
    - docker:dind
  script:
    - echo "${DOCKER_HOST}"
    - apt-get update
    - apt-get install -y curl
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose up -d
    - mvn clean test -Dspring.profiles.active=remote

report_a:
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/
    expire_in: 1 week
    when: always
  needs:
    - test_a

report_b:
  stage: report
  script:
    - mvn cluecumber-report:reporting
  artifacts:
    paths:
      - target/
    expire_in: 1 week
    when: always
  needs:
    - test_b
